theme: jekyll-theme-cayman
title: Introduction to Machine Learning
description: Course at University of Bremen's <a href="https://www.informatica-feminale.de/eng/registration-2018-is-open/">Informatica Feminale 2018</a>
